### ISSUE TITLE
Refactor  azure-core-v2 HttpRetryOptions

### ISSUE THREAD

**Issue by samvaity** [Azure/azsdk-java-rewrite-recipes#3]
Task 1:
The HttpRetryOptions from aure-core-v2 no longer need to be specified using the model classes `FixedDelay` or `ExponentialDelay`.
The HttpRetryOptions can be used with two constructors 2 args(Fixed Delay) and 3 args constructor(Exponential Delay) 

```[tasklist]
### Tasks
- [ ] Update to use constructor args on builder API
- [ ] Add http prefix to Builder API retryOptions
```

**Comment by AliSoltanianFJ** [comment]
Completed in PR #12
